# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kodongpd' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kodongpd

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'PINRemoteImage', '3.0.0-beta.13'
  pod 'SVProgressHUD', '~> 2.2'
  pod 'Alamofire', '5.0.0.beta.1'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  
end
